"""users table

Revision ID: 5587a7a895cc
Revises: 65340b60255f
Create Date: 2023-12-19 19:14:20.989119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5587a7a895cc'
down_revision = '65340b60255f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.drop_index('ix_user_phone')
        batch_op.drop_index('ix_user_user_surname')
        batch_op.drop_column('user_surname')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('user_surname', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_user_user_surname', ['user_surname'], unique=False)
        batch_op.create_index('ix_user_phone', ['phone'], unique=False)
        batch_op.create_index('ix_user_email', ['email'], unique=False)

    # ### end Alembic commands ###
