"""users table

Revision ID: 684be1070e72
Revises: 5587a7a895cc
Create Date: 2023-12-19 19:23:59.187556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684be1070e72'
down_revision = '5587a7a895cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_user_user_name')
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=False)
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index('ix_user_user_name', ['user_name'], unique=False)
        batch_op.drop_column('username')

    # ### end Alembic commands ###
